run:
  timeout: 3m

linters:
  enable:
    - errcheck
    - staticcheck
    - gosec
    - ineffassign
    - unused
    - govet
    - revive

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
